# Generated by Django 5.2.7 on 2025-10-08 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='uploads/')),
                ('predicted_class', models.CharField(max_length=100)),
                ('model_used', models.CharField(max_length=100)),
                ('prediction_confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Classification Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
